TILE_SIZE = 32  # Taille d'une tuile en pixels
SCREEN_WIDTH = 26 * TILE_SIZE
SCREEN_HEIGHT = 27 * TILE_SIZE
CHILDREN_COUNT = 6

CHILDREN_POS = [
    (6 * TILE_SIZE, 7 * TILE_SIZE), (10 * TILE_SIZE, 4 * TILE_SIZE),
    (9 * TILE_SIZE, 7 * TILE_SIZE), (1 * TILE_SIZE, 10 * TILE_SIZE),
    (5 * TILE_SIZE, 16 * TILE_SIZE), (6 * TILE_SIZE, 3 * TILE_SIZE)
]
TOYBOX_POS = (15 * TILE_SIZE, 22 * TILE_SIZE)
DISPLAY_PATH = True
USE_PLAYER = False
MIN_HUNGRY_TIMER = 5
MAX_HUNGRY_TIMER = 20